### PR TITLE
refactoring audio and video assets and helpers

### PR DESCRIPTION
**Pull request by ShaunFrost**
Related issue: #18 

**Description**

A parent class PlayableMediaAsset was created to contain common variables and methods for Audio and Video Assets.
The AudioAsset and VideoAsset classes inherit from PlayableMediaAsset. Any logic that is specific to either of these classes is moved to those classes.

A parent class PlayableMediaAssetHelper class is created. AudioAssetHelper and VideoAsset helper classes inherit from it. Class specific functionalities are kept in the classes and common functionalities are moved to the parent class.

Please advise on any recommendations.

### CODE REVIEW

**Comment by kalegd** [comment]
Thank you so much @ShaunFrost! I tested everything out and it functionally works great. I do have a few stylistic recommendations before merging this PR if you don't mind

* Instead of having a `_setMedia(...)` function, can we just rename both `_audio` and `_video` to `_media`?
* The `PEER_READY` subscription can be in `PlayableMediaAsset`'s `addPartySubscription()` so we don't need to override it in `AudioAsset` nor have that subscription in VideoAsset
* I see why you made PLAY, PAUSE, and STOP object level parameters so they can be referenced easily by AudioAsset and VideoAsset, however they're really constants that don't need to be set at the object level. How about we create a new Enum like `/scripts/core/enums/PlayableMediaActions.js`?
* No need to pass in an empty string in your call to `publishMessage` (good idea btw on creating a separate function for that)
* Please run `npm run lint` to make sure everything conforms to the project's preferred style
* Let's move `play`, `pause`, `stop`, and `_onPeerReady` all to `PlayableMediaAsset`. We can make this easy by adding the following functions to PlayableMediaAsset that should get overridden by AudioAsset and VideoAsset
```
    isPlaying() {
        console.error("PlayableMediaAsset.isPlaying() should be overridden");
    }

    getProgress() {
        console.error("PlayableMediaAsset.getProgress() should be overridden");
    }

    setProgress(progress) {
        console.error("PlayableMediaAsset.setProgress() should be overridden");
    }
```
(We can then just rename VideoAsset's _isPlaying() to isPlaying() )

**Comment by kalegd** [comment]
Oh last thing, could we rename your `publishMessage` to `publishPartyMessage`? This may help avoid any confusion in the future as Party messages and Internal messages via PubSub are handled differently

**Comment by ShaunFrost** [comment]
Hey @kalegd, thanks for the awesome suggestions! Some of those came across my mind initially and I should have discussed it a little more. I was thinking of making the PlayableMediaAsset class more abstract as well. I have applied the aforementioned changes in your comment and tested few functionalities in my local. Ran the lint check and corrected the warnings. Let me know if you have any other recommendations.

**Comment by kalegd** [comment]
Thanks a bunch for your help! Would you like to be added to the contributors list in the README?

**Comment by ShaunFrost** [comment]
@kalegd definitely! Would love to be part of the list. Looking forward to contribute more to this!

**Comment by kalegd** [comment]
@all-contributors please add @ShaunFrost for code

**Comment by kalegd** [comment]
Glad to hear you're interested in contributing more! I have a big refactoring I'm going to be starting soon regarding UI, but once that's finished I'll put more tasks up for grabs ideally towards the end of April

**Comment by ShaunFrost** [comment]
@kalegd that sounds exciting! I'll keep an eye out.

**Pull request merged**
