### PR TITLE
Feature/testing pointer interactable

### PR DESCRIPTION
**Pull request by justjo3l**
Related issue: #32 

**Description**

This pull request contains the required tests as recommended in the issue. In order to make testing possible, the following changes have been implemented alongside.
- JSDOM environment was installed and set up.
- Import referencing throughout the used files were updated.
- The required tests were added.

Please advise if any recommendations!

### CODE REVIEW

**Comment by kalegd** [comment]
Fantastic! Thank you for capturing all the test cases. I just have 3 things I'd like changed before merging
1. Instead of rewriting the import statements of source files to use relative paths, can you just add some `moduleNameMapper` to the package.json like so to fix the absolute path issue in jest?
```
"jest": {
  "testEnvironment": "jsdom",
  "moduleNameMapper": {
      "/scripts/(.*)": "<rootDir>/scripts/$1",
      "/node_modules/(.*)": "<rootDir>/node_modules/$1"
  }
}
```
2. Even though it's a passthrough variable that isn't used directly by PointerInteractable, closestPoint is expected to be a Vector3 object throughout the application, so can we change its initialization to something like `const sampleClosestPoint = new THREE.Vector3();`?
3. Similar to the above statement, can your `createThreeObj()` return an actual three.js object? Like `new THREE.Object3D()`?

**Comment by justjo3l** [comment]
Thanks for the recommendations! I have implemented such and committed the changes.

Please let me know if you have any more recommendations!

**Comment by kalegd** [comment]
@all-contributors please add @justjo3l for test

**Comment by kalegd** [comment]
Thank you @justjo3l , I've gone ahead and added you to the README as a contributor. Sorry, I usually mean to ask people before I do that, if you'd like yourself removed please let me know!

**Comment by justjo3l** [comment]
All good! Thanks for the opportunity to contribute!

**Pull request merged**
